### ISSUE TITLE
disabled buttons

### ISSUE THREAD

**Issue by konsumer** [ajainvivek/preact-fluid#11]
I am doing something like this:

```css
button:disabled,
button[disabled]{
  background: #eee;
  color: #666;
  border-color: #777;
}
```

To get disabled buttons looking right. Is there interest in putting this in a PR for the button CSS?
